// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import { config } from "dotenv";

config({ path: path.resolve(process.cwd(), ".env") });

import { defineConfig } from "prisma/config";

// Use DIRECT_URL for migrations (required by Neon); fall back to DATABASE_URL
const migrationUrl =
  process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl,
  },
});
